services:
  snowluma:
    image: motricseven7/snowluma:latest
    container_name: snowluma
    restart: unless-stopped
    shm_size: 1gb
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    environment:
      VNC_PASSWD: ${VNC_PASSWD:-vncpasswd}
      TZ: Asia/Shanghai
      SNOWLUMA_WEBUI_HOST: 0.0.0.0
      SNOWLUMA_WEBUI_PORT: 5099
      SNOWLUMA_HOOK_AUTOLOAD: 1
      SNOWLUMA_ACCEPT_EULA: 1
      SNOWLUMA_ACCEPT_PRIVACY: 1
      SNOWLUMA_LOG_LEVEL: info
      SNOWLUMA_QQ_FLAGS: "--disable-gpu --disable-software-rasterizer --disable-gpu-compositing"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:5099:5099"
      - "127.0.0.1:6081:6081"
      - "127.0.0.1:5900:5900"
    volumes:
      - qq-gateway-data:/app/data
      - qq-client-config:/app/.config
      - qq-client-data:/app/.local/share
volumes:
  qq-gateway-data:
  qq-client-config:
  qq-client-data:
